[project]
name = "python-dev-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []


[dependency-groups]
dev = [
    "debugpy>=1.8.12",
    "invoke>=2.2.0",
    "ruff>=0.9.6",
]
