version: '3.0'

tasks:
  default:
    cmds:
      - task --list

  uv-start:
    desc: start uv 
    cmds:
      - uv venv
      - uv sync

  format:
    desc: format code
    cmds: 
      - uv run ruff format

  lint:
    desc: lint code
    cmds:
      - uv run ruff check

